FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity_Y:
      id: 3
      type: RLBase
    BFM_goal:
      id: 4
      type: BFM

  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,  
      3,3,3,3,3,3,3,  
    ]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity_Y: RB + Y.on_pressed
      BFM_goal: RT + Y.on_pressed
    kp: [
      100., 100., 100., 150., 40., 40.,
      100., 100., 100., 150., 40., 40.,
      200,200,200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0, 0.25,0,0.97,0.15, 0,0,
        0, -0.25,0,0.97,-0.15, 0,0
      ]
    ]
  Velocity_Y:
    transitions: 
      Passive: LT + B.on_pressed
      BFM_goal: RT + Y.on_pressed
    policy_dir: ../../../logs/g1/velocity/g1_moe_cts_v0.0.5.1

  BFM_goal:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity_Y: RB + Y.on_pressed
    policy_dir: ../../../logs/g1/bfm/official
    deploy_yaml: param/deploy.yaml
    onnx_model: exported/FBcprAuxModel.onnx
    onnx_tensorrt: false
    onnx_cuda: true
    onnx_cuda_device: 0
    waist_kalman:
      enabled: true
      joint_indices: [12, 13, 14]
      process_noise: 1.0e-4
      measurement_noise: 2.0e-3
      initial_error_cov: 1.0e-2
    task_type: goal
    latent_file: goal_inference/goal_reaching.npz
    gamepad_map:
      next_latent: Y.on_pressed
      reset_state: X.on_pressed
    goal:
      selected_goals: [
        fallAndGetUp1_subject4_2193,
        dance1_subject3_505,
        fight1_subject3_5559, 
        fallAndGetUp1_subject4_2193,
      ]
